# Generated by Django 5.0 on 2023-12-13 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_request', models.CharField(max_length=2048)),
                ('answer', models.CharField(max_length=8000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('doc_id', models.CharField(blank=True, max_length=60, null=True)),
                ('file_name', models.CharField(blank=True, max_length=60, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('displayed', models.BooleanField(default=False)),
                ('satisfied', models.BooleanField(default=False)),
                ('comment', models.CharField(default=' ', max_length=300)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.answer')),
            ],
        ),
    ]
