# Generated by Django 5.0 on 2023-12-19 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocRetrivalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_request', models.CharField(max_length=2048)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocRetrivalResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2048)),
                ('score', models.IntegerField(default=0)),
                ('file_name', models.CharField(blank=True, max_length=60, null=True)),
                ('doc_id', models.CharField(blank=True, max_length=60, null=True)),
                ('doc_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.docretrivalrequest')),
            ],
        ),
    ]
