# Generated by Django 5.0 on 2024-01-04 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0003_ingestedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='ingestedfile',
            name='ingestion_session',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestione.ingestionsession'),
            preserve_default=False,
        ),
    ]
