# Generated by Django 5.0 on 2024-01-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0004_ingestionsession_ingestedfile_ingestion_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestedfile',
            name='file_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
