# Generated by Django 5.0 on 2024-01-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0005_ingestedfile_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='comment',
            field=models.CharField(blank=True, default=' ', max_length=300, null=True),
        ),
    ]
