# Generated by Django 5.0 on 2024-01-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0006_alter_question_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docretrivalresponse',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
